# -*- coding: utf-8 -*-
"""Descomplicando a criação de pacotes de processamento de imagens em Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g7bJnRlZ7oPibBNj-Vt6wVC6ssumOv8R
"""

from setuptools import setup, find_packages

with open("README.md", "r") as f:
    page_description = f.read()

with open("requirements.txt") as f:
    requirements = f.read().splitlines()

setup(
    name="image_processing-test",
    version="0.0.2",
    author="Guilherme de Quadros Gabriel Neto",
    author_email="guih.gabriel93@outlook.com",
    description="Test version - Image processing. This project belongs to Karina Tiemi Kato, Tech Lead, Machine Learning Engineer, Data Scientist Specialist at Take. This package is a demo for simulation of upload on the Test Pypi website, and it's from class of the Python Developer     E-mail:karinatkato@gmail.com.",
    long_description=page_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Guih1993?tab=repositories",
    packages=find_packages(),
    install_requires=requirements,
    python_requires='>=3.8',
)